Update nuxtjs.yml

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -18,6 +18,7 @@ env:
   REPO_OWNER: ${{ github.event.repository.owner.login }}
   REPO_NAME: ${{ github.event.repository.name }}
   TOKEN: ${{ secrets.TOKEN_GITHUB }}
+  PROJECT_PATH: "/home/Houzeo"
   APPROVED: false
 
 jobs:
@@ -359,83 +360,90 @@ jobs:
                 }
               ]
             }'
-            
   deploy:
-    name: Deploy Nuxt App
-    runs-on: self-hosted
-    needs: manual_approval
-    if: needs.manual_approval.outputs.approval_status == 'approved'
-    steps:
-      - name: Run deployment script on self-hosted runner
-        run: |
-          pwd
-          ls -l /home/Houzeo/
-          cd /home/Houzeo
-          sudo bash nuxt-deploy.sh
-
-      - name: Get current timestamp
-        id: timestamp
-        run: echo "TIMESTAMP_END=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
-
-      - name: Send Deployment Completed Email via SendGrid
-        run: |
-          curl --request POST \
-            --url https://api.sendgrid.com/v3/mail/send \
-            --header "Authorization: Bearer ${{ env.email_sendgrid_key }}" \
-            --header "Content-Type: application/json" \
-            --data '{
-              "personalizations":  [
-                {
-                  "to": [
-                    {
-                      "email":"${{ env.email_to }}"
-                    }
-                  ],
-                  "subject": "${{ env.email_subject }}"
-                }
-              ],
-              "from": {
-                "email":"${{ env.email_from }}"
-              },
-              "content": [
-                {
-                  "type": "text/html",
-                 
-                  "value": "The <strong>deployment has Completed</strong> for PR <a href='${{ env.PR_URL }}'>#${{ env.PR_NUMBER }}</a><br>PR merged by: <strong>${{ env.PR_MERGED_BY }}</strong><br>Timestamp: <strong>${{ env.TIMESTAMP_END }}</strong>"
-                }
-              ]
-            }'
-      - name: Get current timestamp
-        if: always()
-        id: timestamp_failed
-        run: echo "TIMESTAMP_FAILED=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
-      
-      - name: Send Failure Notification 2
-        if: failure()  # This ensures this step runs only if there's a failure in the previous steps
-        run: |
-          echo "TIMESTAMP_failed=timestamp::$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
-          curl --request POST \
-            --url https://api.sendgrid.com/v3/mail/send \
-            --header "Authorization: Bearer ${{ env.email_sendgrid_key }}" \
-            --header "Content-Type: application/json" \
-            --data '{
-              "personalizations":  [
-                {
-                  "to": [
-                    {
-                      "email":"${{ env.email_to }}"
-                    }
-                  ],
-                  "subject": "${{ env.email_subject }}"
-                }
-              ],
-              "from": {
-                "email":"${{ env.email_from }}"
-              },
-              "content": [
-                {
-                  "type": "text/html",
-                  "value": "The <strong>deployment has <span style='color:red;'>FAILED</span></strong> for PR<a href='${{ env.PR_URL }}'> #${{ env.PR_NUMBER }}</a><br>PR merged by: <strong>${{ env.PR_MERGED_BY }}</strong><br>Timestamp: <strong>${{ env.TIMESTAMP_FAILED }}</strong><br>Please visit Actions tab to view the Workflow"
-                }
-              ]
-            }'
+      name: Deploy Nuxt App
+      runs-on: self-hosted
+      needs: manual_approval
+      if: needs.manual_approval.outputs.approval_status == 'approved'
+      steps:
+        - name: Check if deployment script exists
+          id: check_script
+          run: |
+            if [ ! -f /home/Houzeo/nuxt-deploy.sh ]; then
+              echo "Deployment script not found"
+              exit 1
+            fi
+  
+        - name: Run deployment script on self-hosted runner
+          run: |
+            pwd
+            ls -l /home/Houzeo/
+            cd /home/Houzeo
+            sudo bash nuxt-deploy.sh
+  
+        - name: Get current timestamp
+          id: timestamp
+          run: echo "TIMESTAMP_END=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
+  
+        - name: Send Deployment Completed Email via SendGrid
+          run: |
+            curl --request POST \
+              --url https://api.sendgrid.com/v3/mail/send \
+              --header "Authorization: Bearer ${{ env.email_sendgrid_key }}" \
+              --header "Content-Type: application/json" \
+              --data '{
+                "personalizations":  [
+                  {
+                    "to": [
+                      {
+                        "email":"${{ env.email_to }}"
+                      }
+                    ],
+                    "subject": "${{ env.email_subject }}"
+                  }
+                ],
+                "from": {
+                  "email":"${{ env.email_from }}"
+                },
+                "content": [
+                  {
+                    "type": "text/html",
+                    "value": "The <strong>deployment has Completed</strong> for PR <a href='${{ env.PR_URL }}'>#${{ env.PR_NUMBER }}</a><br>PR merged by: <strong>${{ env.PR_MERGED_BY }}</strong><br>Timestamp: <strong>${{ env.TIMESTAMP_END }}</strong>"
+                  }
+                ]
+              }'
+  
+        - name: Get current timestamp (Failure timestamp)
+          if: always()
+          id: timestamp_failed
+          run: echo "TIMESTAMP_FAILED=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
+        
+        - name: Send Failure Notification
+          if: failure()  # This ensures this step runs only if there's a failure in the previous steps
+          run: |
+            echo "TIMESTAMP_failed=timestamp::$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
+            curl --request POST \
+              --url https://api.sendgrid.com/v3/mail/send \
+              --header "Authorization: Bearer ${{ env.email_sendgrid_key }}" \
+              --header "Content-Type: application/json" \
+              --data '{
+                "personalizations":  [
+                  {
+                    "to": [
+                      {
+                        "email":"${{ env.email_to }}"
+                      }
+                    ],
+                    "subject": "Nuxt Production Deployment FAILED | PR #${{ env.PR_NUMBER }}"
+                  }
+                ],
+                "from": {
+                  "email":"${{ env.email_from }}"
+                },
+                "content": [
+                  {
+                    "type": "text/html",
+                    "value": "The <strong>deployment has <span style='color:red;'>FAILED</span></strong> for PR<a href='${{ env.PR_URL }}'> #${{ env.PR_NUMBER }}</a><br>PR merged by: <strong>${{ env.PR_MERGED_BY }}</strong><br>Timestamp: <strong>${{ env.TIMESTAMP_FAILED }}</strong><br>Please visit Actions tab to view the Workflow logs."
+                  }
+                ]
+              }'
